# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24edd2256135aad9cd255b4f0b797851218138cf9616d6b5362ca6f115dd168a99e967d3c701f716664c6260d76ec07d68430f7358ac37a61bae02df32f2fff8

test:
  secret_key_base: fcbbe4d9efe912e575bcd70cab647a4472bda95ff20c4560a203f1a83522248de2651cddf12c6188c95e0ba1997c9818ec5075c1ac258f7f8279e70e66c5b1be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
